#!/bin/bash

if [[ -n "$2" ]]; then
    case "$1" in
        "command")
            $2
            ;;
        *)
            echo "Unknown variable $1!"
            exit 1
            ;;
    esac
    echo "SET"
    exit 0
fi
